name: "csvs-to-sqlite"
description: "run csvs-to-sqlite"
inputs:
  arg:
    description: "Arguments to pass to csvs-to-sqlite"
    required: true
    default: "--help"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.arg }}
