name: Tests

on: [push]

env:
  TESTDATA: __tests__/testdata

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test run
    steps:
      - name: Login
        run: echo -n ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin docker.pkg.github.com
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./ # Uses an action in the root directory
        with:
          cli_args: test.csv test.db
          working_directory: ${{ env.TESTDATA }}
      - name: Logout
        run: docker logout docker.pkg.github.com
        if: ${{ always() }}
